### ISSUE TITLE
10월 7일 To-do

### ISSUE THREAD

**Issue by Cheorizzang** [Cheorizzang/testRepo#1]
## To-do
- [ ] 오전 특강 열심히 듣기
- [ ] 점심 맛있게 먹기
- [ ] 오후 특강 열심히 듣기
- [ ] 특강 듣고 주말에 푹 쉬기

**Comment by Cheorizzang** [comment]
이슈를 클로즈한 이유를 정리해서 코멘트를 작성합니다
